### ISSUE TITLE
Breaks because pry is required but not a dependency

### ISSUE THREAD

**Issue by code-later** [wpf-social-coding/batman-ipsum#5]
When running just `batman_ipsum` without args I get the following error:

```
/Users/dbreuer/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pry (LoadError)
        from /Users/dbreuer/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/dbreuer/.gem/ruby/2.3.0/gems/batman_ipsum-0.1.0/lib/batman_ipsum/client.rb:4:in `<top (required)>'
        from /Users/dbreuer/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/dbreuer/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/dbreuer/.gem/ruby/2.3.0/gems/batman_ipsum-0.1.0/lib/batman_ipsum.rb:2:in `<top (required)>'
        from /Users/dbreuer/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/dbreuer/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/dbreuer/.gem/ruby/2.3.0/gems/batman_ipsum-0.1.0/bin/batman_ipsum:3:in `<top (required)>'
        from /Users/dbreuer/.gem/ruby/2.3.0/bin/batman_ipsum:23:in `load'
        from /Users/dbreuer/.gem/ruby/2.3.0/bin/batman_ipsum:23:in `<main>'
```

It looks like you just load Pry as development dependency:

``` ruby
# in batman_ipsum.gemspec
spec.add_development_dependency "pry"
```

**Comment by code-later** [comment]
Fixed in #6
